### ISSUE TITLE
Prediction accuracy is very low!

### ISSUE THREAD

**Issue by azeemabbas** [jayeshsaini/emnist-flask#2]
@jayeshsaini It is good application but the model you have trained has very low accuracy. Nearly all of the writing letters in HTML Canvas are predicted wrong.

Any suggestions? Your code help me in connecting Flask with ML.

Thanks.

**Comment by jayeshsaini** [comment]
@azeemabbas The accuracy can be increased by retraining a better model and on larger number of epochs. I didn't have much time, so for faster implementation, I stopped training with acceptable accuracy to check the entire application.
